<a href="https://colab.research.google.com/github/NagarajaN-Nethi/in/blob/main/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.


In [1]:
def vandermonde(input_vector, n, increasing = True):
    import numpy as np
    input_vector = np.array(input_vector)
    if increasing == False:
        op_matx = np.array([x**(n-1-i) for x in input_vector for i in range(n)]).reshape(input_vector.size,n)
    else:
        op_matx = np.array([x**i for x in input_vector for i in range(n)]).reshape(input_vector.size,n)
    
    return op_matx    

In [2]:
a = [2, 4, 6, 8]
vandermonde(a, 4, False)

array([[  8,   4,   2,   1],
       [ 64,  16,   4,   1],
       [216,  36,   6,   1],
       [512,  64,   8,   1]])

In [3]:
vandermonde(a, 4)

array([[  1,   2,   4,   8],
       [  1,   4,  16,  64],
       [  1,   6,  36, 216],
       [  1,   8,  64, 512]])

In [ ]:
np.vander(x, increasing = True)

array([[   1,    2,    4,    8,   16],
       [   1,    3,    9,   27,   81],
       [   1,    4,   16,   64,  256],
       [   1,    5,   25,  125,  625],
       [   1,    6,   36,  216, 1296]])

Problem Statement 2:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question:
Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [4]:
import numpy as np

In [5]:
test = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
test

array([  3,   5,   7,   2,   8,  10,  11,  65,  72,  81,  99, 100, 150])

In [6]:
def moving_avg(array, window, dropna = True):
    '''
    array : np.array
    winwos : SIZE OF WINDOWS
    '''
    import numpy as np
    import pandas as pd
    if isinstance(array,(np.ndarray, np.generic)) :
        if dropna == True:
            
            return np.array(pd.Series(array).rolling(window).mean().dropna())
            
        else: return np.array(pd.Series(array).rolling(window).mean())
    else: print('Not an Numpy array. Please enter array')

In [7]:
moving_avg(test,3, True)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])